### ISSUE TITLE
DA and rollup color tags display incorrectly

### ISSUE THREAD

**Issue by jcstein** [celestiaorg/modularsummit.dev#44]
<img width="874" alt="Screenshot 2023-07-19 at 17 56 10" src="https://github.com/celestiaorg/modularsummit.dev/assets/46639943/c2ca3d2b-5ced-4220-a512-a4a66d62d792">

this is likely due to a mix of "rollup" and "data-availability" tags, as the schedule was changed

**Comment by gabros20** [comment]
Yeah, it was not design to deal with topic mix up. It's expecting speakers to follow each other with the same theme, the it draws the line to group them. It needs a drawing logic refactor. I will look into it asap.

**Comment by jcstein** [comment]
if big lift for you, it is not a big deal and i understand! thanks for the context

**Comment by gabros20** [comment]
I have the tracks done. But couldn't figure out the label rendering yet, I almost got it right though.
I'm gonna release it without labels for now so it won't look that bad if that's ok. Then I add the labels back later today once I figured it out.

**Comment by gabros20** [comment]
@jcstein Added labels back, not as elegant as originally was but I think it will do the job.
https://modularsummit.dev/

**Comment by jcstein** [comment]
thank you @gabros20 !
